<a href="https://colab.research.google.com/github/lnsayer/udemy_ml_course/blob/main/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [7]:
import torch


# Create random tensor
tensor = torch.rand(7,7)
tensor

tensor([[0.5317, 0.6267, 0.7185, 0.5444, 0.3360, 0.5426, 0.6135],
        [0.6589, 0.0700, 0.0977, 0.8074, 0.9874, 0.9903, 0.2459],
        [0.5063, 0.8075, 0.2920, 0.3285, 0.4903, 0.2151, 0.1000],
        [0.3613, 0.2359, 0.0540, 0.4289, 0.8265, 0.1367, 0.4307],
        [0.6649, 0.7342, 0.6709, 0.1470, 0.0489, 0.0717, 0.7461],
        [0.5450, 0.3020, 0.8280, 0.8980, 0.4072, 0.6292, 0.1046],
        [0.9798, 0.4520, 0.9379, 0.6242, 0.9005, 0.8397, 0.4667]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [9]:
# Create another random tensor
tensor2 = torch.rand(1,7)
# Perform matrix multiplication
torch.matmul(tensor, tensor2.T)

tensor([[1.8194],
        [1.4845],
        [1.1755],
        [0.9990],
        [1.6673],
        [1.7145],
        [2.2373]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [10]:
# Set manual seed
random_seed = 42
torch.manual_seed(random_seed)

# Create two random tensors
tensor1 = torch.rand(7,7)
tensor2 = torch.rand(1,7)

# Matrix multiply tensors
tensor1@tensor2.T

tensor([[1.3299],
        [1.8111],
        [1.3228],
        [0.9725],
        [1.8285],
        [1.4806],
        [2.0489]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [12]:
# Set random seed on the GPU
random_seed = 1234
torch.cuda.manual_seed(random_seed)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [15]:
# Set random seed
random_seed = 1234
torch.cuda.manual_seed(random_seed)

# Check for access to GPU
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

# Create two random tensors on GPU
tensor1 = torch.rand(2,3, device = 'cuda')
tensor2 = torch.rand(2,3, device = 'cuda')
tensor1, tensor2


(tensor([[0.1272, 0.8167, 0.5440],
         [0.6601, 0.2721, 0.9737]], device='cuda:0'),
 tensor([[0.6208, 0.0276, 0.3255],
         [0.1114, 0.6812, 0.3608]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [16]:
# Perform matmul on tensor_A and tensor_B
torch.matmul(tensor1, tensor2.T)

tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [19]:
# Find max
torch.max(torch.matmul(tensor1, tensor2.T))
# Find min
torch.min(torch.matmul(tensor1, tensor2.T))

tensor(0.2786, device='cuda:0')

### 9. Find the maximum and minimum index values of the output of 7.

In [22]:
# Find arg max
print(torch.argmax(torch.mm(tensor1, tensor2.T)))

# Find arg min
torch.argmin(torch.mm(tensor1, tensor2.T))

tensor(1, device='cuda:0')


tensor(0, device='cuda:0')


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [29]:
# Set seed
random_seed = 7
torch.manual_seed(random_seed)

# Create random tensor
tensor = torch.rand(1,1,1,10)

# Remove single dimensions
tensor2 = tensor.squeeze()

# Print out tensors and their shapes
print(tensor.shape, tensor2.shape)
print(tensor, tensor2)


torch.Size([1, 1, 1, 10]) torch.Size([10])
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
