<a href="https://colab.research.google.com/github/lnsayer/udemy_ml_course/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch Fundamentals

Course resources: https://learnpytorch.io/00_pytorch_fundamentals/



In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as  plt
print(torch.__version__)


2.2.1+cu121


## Introduction to Tensors

### Creating tensors

Pytorch tensors are created using ```torch.Tensor()``` = https://pytorch.org/docs/stable/tensors.html

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as Python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7,8], [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX[0]

tensor([7, 8])

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR
TENSOR.shape

torch.Size([1, 3, 3])

In [12]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks is they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update numbers -> look at data -> update numbers`

In [13]:
# Create a random tensor of size (3,4)
random_tensor = torch.randn(3,4)
random_tensor

tensor([[-0.0247,  0.3529,  0.2331, -0.1290],
        [-0.8837, -0.0900, -2.5043, -1.1614],
        [-1.7630,  0.8554, -0.6076,  0.2949]])

In [14]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(3, 224, 224) # height, width, colour channels(RGB)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

# Zeros and ones

In [15]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [16]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [17]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [27]:
# Use torch.arange()
one_to_ten = torch.arange(start=0,end=1000, step = 77)
one_to_ten, one_to_ten.ndim

(tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924]), 1)

In [19]:
# Creating tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Tensor datatypes


In [20]:
# Float_32_tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what data type is the tensor, e.g.float32 or float16
                               device = None, # what device your tensor is on
                               requires_grad=False) # whether or not to track gradients with this tensor's operations

In [21]:
float_32_tensor

tensor([3., 6., 9.])

### Tensor datatypes

**Note:** Tensor datatypes is one of the the big errors you'll run into with Pytorch with deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [22]:
float_32_tensor.dtype

torch.float32

In [23]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [24]:
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [28]:
float_tensor = float_16_tensor * float_32_tensor
float_tensor.dtype

torch.float32

In [34]:
int_32_tensor = torch.tensor([3,4,5], dtype=torch.long)
int_32_tensor

tensor([3, 4, 5])

In [35]:
(float_32_tensor * int_32_tensor).dtype

torch.float32

### Getting information from tensors (attributes)

1. Tensors not right datatype - to get datatype from a tensor can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from tensor, can use `tensor.device`

In [38]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.8879, 0.7319, 0.8919, 0.3928],
        [0.5604, 0.7046, 0.6433, 0.5515],
        [0.1203, 0.5918, 0.0904, 0.7074]])

In [40]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.8879, 0.7319, 0.8919, 0.3928],
        [0.5604, 0.7046, 0.6433, 0.5515],
        [0.1203, 0.5918, 0.0904, 0.7074]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


from ast import Add
### Manipulating Tensors (tensor operations)

Tensor operations include:
 - Addition
 - Subtraction
 - Multiplication (element-wise)
 - Division
 - Matrix Multiplication

In [42]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [44]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [45]:
# Subtraction
tensor - 10

tensor([-9, -8, -7])

In [47]:
# Try out Pytorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix Multiplication

Two ways of performing multiplicaiton in neural networks and deep learning:
- Element-wise multiplication
- Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisy:
1. The **inner dimension** need to satisfy
- `(3,2) @ (3,2)` will not work
- `(2,3) @ (3,2)` will work
- `(3,2) @ (2,3)` will work

2. The resulting matrix has the shape of the **outer dimensions**
- `(2,3) @ (3,2)` -> `(2,2)`

In [49]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [50]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [51]:
# Matrix multiplication by hand
1*1+2*2+3*3

14

In [52]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 6.52 ms, sys: 0 ns, total: 6.52 ms
Wall time: 8.33 ms


In [53]:
%%time
torch.mul(tensor, tensor)

CPU times: user 160 µs, sys: 0 ns, total: 160 µs
Wall time: 168 µs


tensor([1, 4, 9])

### One of the most common errors in deep learning: shape errors


In [56]:
# Shapes for matrix multiplication
tensor_a = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_b = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])
# torch.mm(tensor_a, tensor_b) # tensor.mm is the same as torch.matmul (it's an alias for matmul)
# torch.mm(tensor_a, tensor_b) gives error


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

# To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**

In [57]:
tensor_b.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [64]:
# The matrix multiplication operation works when tensor_b is transposed

torch.mm(tensor_a, tensor_b.T).shape
print(f"New shapes: tensor_a = {tensor_a.shape} (same above), tensor_b.T = {tensor_b.T}")
print(f"Multipliying: {tensor_a.shape} @ {tensor_b.T.shape} <- inner dimensions must match")
print("Output: \n")
output = torch.mm(tensor_a, tensor_b.T)
print(output)
print(f"\nOutput shape: {output.shape}")

New shapes: tensor_a = torch.Size([3, 2]) (same above), tensor_b.T = tensor([[ 7,  8,  9],
        [10, 11, 12]])
Multipliying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output: 

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])
