<a href="https://colab.research.google.com/github/lnsayer/udemy_ml_course/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch Fundamentals

Course resources: https://learnpytorch.io/00_pytorch_fundamentals/



In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as  plt
print(torch.__version__)


2.2.1+cu121


## Introduction to Tensors

### Creating tensors

Pytorch tensors are created using ```torch.Tensor()``` = https://pytorch.org/docs/stable/tensors.html

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as Python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7,8], [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX[0]

tensor([7, 8])

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR
TENSOR.shape

torch.Size([1, 3, 3])

In [12]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks is they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update numbers -> look at data -> update numbers`

In [13]:
# Create a random tensor of size (3,4)
random_tensor = torch.randn(3,4)
random_tensor

tensor([[ 0.5718,  1.2239, -0.6883, -1.2713],
        [-0.0347,  0.8797, -0.8620, -0.2395],
        [ 0.4723, -0.0047,  0.1607,  0.5780]])

In [14]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(3, 224, 224) # height, width, colour channels(RGB)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

# Zeros and ones

In [15]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [16]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [17]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [22]:
# Use torch.arange()
one_to_ten = torch.range(start=0,end=1000, step = 77)
one_to_ten

<ipython-input-22-5d2b79287a8b>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  one_to_ten = torch.range(start=0,end=1000, step = 77)


tensor([  0.,  77., 154., 231., 308., 385., 462., 539., 616., 693., 770., 847.,
        924.])

In [23]:
# Creating tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Tensor datatypes


In [29]:
# Float_32_tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what data type is the tensor, e.g.float32 or float16
                               device = None, # what device your tensor is on
                               requires_grad=False) # whether or not to track gradients with this tensor's operations

In [28]:
float_32_tensor

tensor([3., 6., 9.])

### Tensor datatypes

**Note:** Tensor datatypes is one of the thre big errorrs you'll run into with Pytorch with deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [30]:
float_32_tensor.dtype

torch.float32

In [32]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [33]:
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [34]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])