<a href="https://colab.research.google.com/github/lnsayer/udemy_ml_course/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch Fundamentals

Course resources: https://learnpytorch.io/00_pytorch_fundamentals/



In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as  plt
print(torch.__version__)


2.2.1+cu121


## Introduction to Tensors

### Creating tensors

Pytorch tensors are created using ```torch.Tensor()``` = https://pytorch.org/docs/stable/tensors.html

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

In [6]:
# Get tensor back as Python int
scalar.item()

7

In [8]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [10]:
vector.ndim

1

In [12]:
vector.shape

torch.Size([2])

In [17]:
# MATRIX
MATRIX = torch.tensor([[7,8], [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [18]:
MATRIX[0]

tensor([7, 8])

In [20]:
MATRIX.shape

torch.Size([2, 2])

In [24]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR
TENSOR.shape

torch.Size([1, 3, 3])

In [25]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])