<a href="https://colab.research.google.com/github/lnsayer/udemy_ml_course/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch Fundamentals

Course resources: https://learnpytorch.io/00_pytorch_fundamentals/



In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as  plt
print(torch.__version__)


2.2.1+cu121


## Introduction to Tensors

### Creating tensors

Pytorch tensors are created using ```torch.Tensor()``` = https://pytorch.org/docs/stable/tensors.html

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as Python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7,8], [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX[0]

tensor([7, 8])

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR
TENSOR.shape

torch.Size([1, 3, 3])

In [12]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks is they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update numbers -> look at data -> update numbers`

In [13]:
# Create a random tensor of size (3,4)
random_tensor = torch.randn(3,4)
random_tensor

tensor([[ 0.2176, -0.7204,  0.3259,  0.1515],
        [-1.8375, -1.0147, -0.6232, -0.0535],
        [ 0.7640,  0.1896, -0.3826, -2.4228]])

In [14]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(3, 224, 224) # height, width, colour channels(RGB)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

# Zeros and ones

In [15]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [16]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [17]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [18]:
# Use torch.arange()
one_to_ten = torch.arange(start=0,end=1000, step = 77)
one_to_ten, one_to_ten.ndim

(tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924]), 1)

In [19]:
# Creating tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes


In [20]:
# Float_32_tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what data type is the tensor, e.g.float32 or float16
                               device = None, # what device your tensor is on
                               requires_grad=False) # whether or not to track gradients with this tensor's operations

In [21]:
float_32_tensor

tensor([3., 6., 9.])

### Tensor datatypes

**Note:** Tensor datatypes is one of the the big errors you'll run into with Pytorch with deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [22]:
float_32_tensor.dtype

torch.float32

In [23]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [24]:
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [25]:
float_tensor = float_16_tensor * float_32_tensor
float_tensor.dtype

torch.float32

In [26]:
int_32_tensor = torch.tensor([3,4,5], dtype=torch.long)
int_32_tensor

tensor([3, 4, 5])

In [27]:
(float_32_tensor * int_32_tensor).dtype

torch.float32

### Getting information from tensors (attributes)

1. Tensors not right datatype - to get datatype from a tensor can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from tensor, can use `tensor.device`

In [28]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.9632, 0.8056, 0.4740, 0.0311],
        [0.0043, 0.6645, 0.9285, 0.8759],
        [0.6115, 0.5644, 0.4302, 0.6121]])

In [29]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.9632, 0.8056, 0.4740, 0.0311],
        [0.0043, 0.6645, 0.9285, 0.8759],
        [0.6115, 0.5644, 0.4302, 0.6121]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


from ast import Add
### Manipulating Tensors (tensor operations)

Tensor operations include:
 - Addition
 - Subtraction
 - Multiplication (element-wise)
 - Division
 - Matrix Multiplication

In [30]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [31]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [32]:
# Subtraction
tensor - 10

tensor([-9, -8, -7])

In [33]:
# Try out Pytorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix Multiplication

Two ways of performing multiplicaiton in neural networks and deep learning:
- Element-wise multiplication
- Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisy:
1. The **inner dimension** need to be the same
- `(3,2) @ (3,2)` will not work
- `(2,3) @ (3,2)` will work
- `(3,2) @ (2,3)` will work

2. The resulting matrix has the shape of the **outer dimensions**
- `(2,3) @ (3,2)` -> `(2,2)`

In [34]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [35]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [36]:
# Matrix multiplication by hand
1*1+2*2+3*3

14

In [37]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.51 ms, sys: 956 µs, total: 2.47 ms
Wall time: 18.2 ms


In [38]:
%%time
torch.mul(tensor, tensor)

CPU times: user 917 µs, sys: 9 µs, total: 926 µs
Wall time: 3.49 ms


tensor([1, 4, 9])

### One of the most common errors in deep learning: shape errors


In [39]:
# Shapes for matrix multiplication
tensor_a = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_b = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])
# torch.mm(tensor_a, tensor_b) # tensor.mm is the same as torch.matmul (it's an alias for matmul)
# torch.mm(tensor_a, tensor_b) gives error


# To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**

In [40]:
tensor_b.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [41]:
# The matrix multiplication operation works when tensor_b is transposed

torch.mm(tensor_a, tensor_b.T).shape
print(f"New shapes: tensor_a = {tensor_a.shape} (same above), tensor_b.T = {tensor_b.T.shape}")
print(f"Multipliying: {tensor_a.shape} @ {tensor_b.T.shape} <- inner dimensions must match")
print("Output: \n")
output = torch.mm(tensor_a, tensor_b.T)
print(output)
print(f"\nOutput shape: {output.shape}")

New shapes: tensor_a = torch.Size([3, 2]) (same above), tensor_b.T = torch.Size([2, 3])
Multipliying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output: 

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, sum, etc (tensor aggregration)



In [42]:
# create a tensor
x= torch.arange(0,100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [43]:
# Find the min, max
torch.min(x), torch.max(x)

(tensor(0), tensor(90))

In [44]:
# Find the mean - note the torch.mean() functions requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32))

tensor(45.)

In [45]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max


In [46]:
# Find the position in tensor that has the minimum values with argmin()
# -> returns index position of target tensor where minimum values occurs
x.argmin(), x.argmax()

(tensor(0), tensor(9))

## Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory
* Stacking - combine multiple tensors on top of each other (vstack or hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input wiht dimensions permuted (swapped) in a certain way

In [47]:
# Let's create a tenso
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [48]:
# Add an extra dimension
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [49]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [50]:
# Changing z changes x (because a view of a tensor shares the same memory as the input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [51]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [52]:
# torch.squeeze - removes all single dimensions from a target tensor
x_reshaped
print(f"previous tensor: {x_reshaped}")
print(f"previous shape: {x_reshaped.shape}")

# remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape {x_squeezed.shape}")

previous tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
previous shape: torch.Size([9, 1])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape torch.Size([9])


In [53]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim(dimension)
print(f"previous target {x_squeezed}")
print(f"previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

previous target tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
previous shape: torch.Size([9])

New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])


In [54]:
x_reshaped.shape

torch.Size([9, 1])

In [55]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [85]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]
# print(x_original)
# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1)# shifts axis 0->1, 1->2, 2->0
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [colour_channels, height, width]
#print(x_permuted)

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [57]:
# They share the same memory:
x_original[0,1, 2] = 0.87
x_permuted[2, 0, 1]

tensor(0.8700)

## Indexing (selecting data from tensors)

Indexing with Pytorch is similar to NumPy.

In [58]:
# Create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [59]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [60]:
# Let's index on the middle bracket (dim =1)
x[0][0], x[0,0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [61]:
# Let's index on the most inner bracket (last dimension)
x[0][2][2]

tensor(9)

In [62]:
# You can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [63]:
# Get all values of 0th and 1st dimension but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [64]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [65]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [66]:
# Index on x to return 9
x[0, 2, 2]

# Index on x to return 3,6,9
x[0, :, 2]

tensor([3, 6, 9])

## Pytorch tensors and NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, Pytorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> 'torch.from_nump(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()

In [67]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.,8.)
tensor = torch.from_numpy(array).type(torch.float32) # warning when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [68]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float32)

In [69]:
# Change the value of array, what will this do to `tensor`?

array = array+1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [70]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [71]:
# Change the tensor, what happens to `numpy_tensor`?
tensor = tensor+1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take the random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again...

To reduce the randomness in neural networks and PyTorch comes the concept of a random seed.

Essentially what a random seed does is "flavour" the randomness.

In [88]:
import torch

# Create two random tensors
tensor_a = torch.rand(3,3)
tensor_b = torch.rand(3,3)

print(tensor_a)
print(tensor_b)
print(tensor_a == tensor_b)

tensor([[0.6568, 0.7708, 0.1053],
        [0.1467, 0.1932, 0.9118],
        [0.1488, 0.0913, 0.4470]])
tensor([[0.2440, 0.5571, 0.1928],
        [0.0602, 0.5837, 0.0009],
        [0.7581, 0.5817, 0.4338]])
tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])


In [91]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
random_seed = 42
torch.manual_seed(random_seed)

random_tensor_c = torch.rand(3,4)
# torch.manual_seed(random_seed)
random_tensor_d = torch.rand(3,4)

print(random_tensor_c)
print(random_tensor_d)

print(random_tensor_c == random_tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


# Extra resources for reproducibility:
* https://pytorch.org/docs/stable/notes/randomness.html


## Running tensors and PyTorch objects on GPUs (and making faster computations)
GPUs = faster computation on numbers, thanks to CUDA + NVIDIA + PyTorch working behind the scenes to make everything hunky dory

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options: https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2, 3 PyTorch +GPU drivers (CUDA) takes a little bit of time of setting up, to do this, refer to PyTorch setup documentation https://pytorch.org/get-started/locally/



In [74]:
!nvidia-smi

Thu Apr  4 09:17:44 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   56C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### 2. Check for GPU access with PyTorch

In [75]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code:
https://pytorch.org/docs/stable/notes/cuda.html#best-practices

e.g. run on GPU if available, else default to CPU

In [76]:
# Setup device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [77]:
# Count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using the GPU results in faster computations.


In [78]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3], device = 'cpu')

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [79]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [80]:
# If tensor is on GPU, cannot transform it to NumPy
# tensor_on_gpu.numpy()

In [81]:
# To fix the GPU tensor with NumPy issue, we cand first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()

In [93]:
tensor_back_on_cpu

array([1, 2, 3])

In [83]:
## Exercises and Extra-curriculum
