In [1]:
import numpy as np

In [3]:
array = np.array([ [[1],[2],[3]], [[4],[5],[6]], [[7],[8],[9]] ])
print(array)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]


In [10]:
print(array.ndim)
print(array.dtype)
print(array.mean())

3
int64
5.0


In [13]:
range_array = np.arange(0,10,2)
print(range_array)

array([0, 2, 4, 6, 8])

In [17]:
#returns random array of integers from low to high
random_array = np.random.randint(0,10, size=(2,4,5))
random_array

array([[[3, 0, 7, 4, 9],
        [6, 7, 7, 4, 5],
        [2, 4, 4, 7, 3],
        [5, 2, 4, 0, 8]],

       [[3, 4, 7, 3, 2],
        [7, 9, 3, 9, 6],
        [0, 5, 3, 6, 7],
        [1, 0, 4, 9, 2]]])

In [20]:
#returns random floats in interval 0 -> 1 in a given size
random_array_2 = np.random.random((3,5))
random_array_2

array([[0.17284105, 0.05634634, 0.9042178 , 0.81069811, 0.76345164],
       [0.3024105 , 0.11502537, 0.73778936, 0.9354562 , 0.9190674 ],
       [0.19102413, 0.06048023, 0.99877189, 0.68777002, 0.04766476]])

In [23]:
random_array_3 = np.random.rand(3,5)
random_array_3

array([[0.28867258, 0.7092264 , 0.7892334 , 0.57599781, 0.90795848],
       [0.11190968, 0.88267142, 0.43451126, 0.28122804, 0.14707488],
       [0.21134266, 0.14537437, 0.83603017, 0.74106416, 0.69621644]])