In [2]:
import numpy as np
import pandas as pd

In [3]:
a1 = np.array([1,2,3])
a2 = np.array([[1,2,3],[4,5,6]])
a3 = np.array([[ [1,2,3], [4,5,6], [7,8,9] ]  ,  [ [10,11,12],[13,14,15],[16,17,18] ]])
print(a1,a2,a3)

[1 2 3] [[1 2 3]
 [4 5 6]] [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [4]:
print(a3.ndim)
print(a3.dtype)
print(a3.mean())

3
int64
9.5


In [5]:
range_array = np.arange(0,10,2)
print(range_array)

[0 2 4 6 8]


In [6]:
#returns random array of integers from low to high
random_array = np.random.randint(0,10, size=(2,4,5))
random_array

array([[[3, 4, 7, 0, 9],
        [4, 4, 4, 8, 3],
        [6, 5, 2, 0, 2],
        [2, 2, 2, 1, 4]],

       [[1, 0, 8, 3, 8],
        [9, 3, 1, 3, 4],
        [6, 6, 1, 7, 2],
        [3, 1, 8, 9, 1]]])

In [7]:
#returns random floats in interval 0 -> 1 in a given size
random_array_2 = np.random.random((3,5))
random_array_2

array([[4.69882065e-01, 9.36873973e-01, 7.73620447e-01, 3.06514562e-02,
        9.28875304e-01],
       [4.47254340e-01, 5.89878706e-01, 9.46981115e-01, 3.97652476e-01,
        1.93891195e-01],
       [9.21419317e-01, 6.33054514e-01, 7.74564302e-04, 7.84742082e-01,
        7.82790383e-01]])

In [8]:
random_array_3 = np.random.rand(3,5)
random_array_3

array([[0.88039081, 0.15225768, 0.90186062, 0.10273391, 0.45676586],
       [0.10963207, 0.17159172, 0.83039075, 0.93822195, 0.21482688],
       [0.47841771, 0.16369625, 0.63588907, 0.17348817, 0.02788702]])

In [9]:
#pseudo random
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [10]:
np.random.seed(7)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

## 3. Viewing arrays and matrices

In [11]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
a1[0]

1

In [13]:
a2.shape

(2, 3)

In [14]:
a2[0]

array([1, 2, 3])

In [15]:
a3.shape

(2, 3, 3)

In [16]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
 a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [18]:
a4 = np.random.randint(10, size = (2,3,4,5))
a4.shape, a4.ndim, a4

((2, 3, 4, 5),
 4,
 array([[[[3, 5, 8, 8, 7],
          [5, 0, 0, 2, 8],
          [9, 6, 4, 9, 7],
          [3, 3, 8, 3, 0]],
 
         [[1, 0, 0, 6, 7],
          [7, 9, 3, 0, 7],
          [7, 7, 0, 5, 4],
          [3, 1, 3, 1, 3]],
 
         [[4, 3, 1, 9, 5],
          [9, 1, 2, 3, 2],
          [2, 5, 7, 3, 0],
          [9, 9, 3, 4, 5]]],
 
 
        [[[3, 0, 4, 8, 6],
          [7, 2, 7, 3, 8],
          [6, 6, 5, 6, 5],
          [7, 1, 5, 4, 4]],
 
         [[9, 9, 0, 6, 2],
          [6, 8, 2, 4, 1],
          [6, 1, 5, 1, 6],
          [9, 8, 6, 5, 9]],
 
         [[7, 5, 4, 9, 6],
          [8, 1, 5, 5, 8],
          [3, 7, 7, 9, 4],
          [7, 5, 9, 6, 2]]]]))

In [19]:
a4[1,1,0], a4[0,2,1,1:4]


(array([9, 9, 0, 6, 2]), array([1, 2, 3]))

In [20]:
#get the first 4 numbers of the inner most arraya
a4[:,:,:,:4]

array([[[[3, 5, 8, 8],
         [5, 0, 0, 2],
         [9, 6, 4, 9],
         [3, 3, 8, 3]],

        [[1, 0, 0, 6],
         [7, 9, 3, 0],
         [7, 7, 0, 5],
         [3, 1, 3, 1]],

        [[4, 3, 1, 9],
         [9, 1, 2, 3],
         [2, 5, 7, 3],
         [9, 9, 3, 4]]],


       [[[3, 0, 4, 8],
         [7, 2, 7, 3],
         [6, 6, 5, 6],
         [7, 1, 5, 4]],

        [[9, 9, 0, 6],
         [6, 8, 2, 4],
         [6, 1, 5, 1],
         [9, 8, 6, 5]],

        [[7, 5, 4, 9],
         [8, 1, 5, 5],
         [3, 7, 7, 9],
         [7, 5, 9, 6]]]])

## 4. Manipulating and comparing arrays

### Arithmetic

In [21]:
a1

array([1, 2, 3])

In [22]:
ones = np.ones(3)
a1+ones

array([2., 3., 4.])

In [23]:
a1*ones

array([1., 2., 3.])

In [24]:
print(a1,a2)
a1.shape, a2.shape

[1 2 3] [[1 2 3]
 [4 5 6]]


((3,), (2, 3))

In [25]:
a2*a1, a1*a2

(array([[ 1,  4,  9],
        [ 4, 10, 18]]),
 array([[ 1,  4,  9],
        [ 4, 10, 18]]))

In [26]:
a2, a3

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]))

In [27]:
a2*a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [28]:
print(a2,)
a4 = np.append(a2, np.array([[7,8,9]]), axis = 0)
print(a4)

a5 = np.append(a2, np.array([[7],[8]]), axis = 1)
print(a5)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 7]
 [4 5 6 8]]


In [29]:
a4*a3

array([[[  1,   4,   9],
        [ 16,  25,  36],
        [ 49,  64,  81]],

       [[ 10,  22,  36],
        [ 52,  70,  90],
        [112, 136, 162]]])

In [30]:
a2/a1

array([[1. , 1. , 1. ],
       [4. , 2.5, 2. ]])

In [31]:
#Floor division removes the deciamls(rounds down)
a2//a1

array([[1, 1, 1],
       [4, 2, 2]])

In [32]:
np.add(a1, ones)

array([2., 3., 4.])

In [33]:
a1+ones

array([2., 3., 4.])

In [34]:
a1 % 2

array([1, 0, 1])

In [35]:
a1/2

array([0.5, 1. , 1.5])

In [36]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [37]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

# Aggregation 

Aggregation = performing the same operation on a number of things

In [38]:
listy_list = [1, 2, 3]

Use Python's methods (`sum()`) on Python datatypes and use Numpy's methods on Numpy arrays (`np.sum()`)

In [39]:
# Create a massive NumPy array
massive_array = np.random.random(100000)
massive_array.size

100000

In [40]:
%timeit sum(massive_array) # Python's sum()
%timeit np.sum(massive_array) # Numpy's np.sum()

3.77 ms ± 34.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
18.6 µs ± 58.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [41]:
np.std(a2)

1.707825127659933

In [42]:
np.var(a2)

2.9166666666666665

### Reshaping and transposing

In [43]:
a2, a3

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]))

In [44]:
a2*a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [45]:
a2.reshape(2,3,1).shape

(2, 3, 1)

In [46]:
a3.shape

(2, 3, 3)

In [47]:
a2_reshape = a2.reshape(2,3,1)
print(a2_reshape)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]


In [48]:
a2_reshape * a3

array([[[  1,   2,   3],
        [  8,  10,  12],
        [ 21,  24,  27]],

       [[ 40,  44,  48],
        [ 65,  70,  75],
        [ 96, 102, 108]]])

In [49]:
#Transpose = switches the axes
a2.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [50]:
a3.T.shape

(3, 3, 2)

## Dot product 

In [51]:
np.random.seed(0)
mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))
mat1, mat2

(array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6],
        [8, 8, 1]]),
 array([[6, 7, 7],
        [8, 1, 5],
        [9, 8, 9],
        [4, 3, 0],
        [3, 5, 0]]))

In [52]:
# Element-wise multiplication (Hadamard product)
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [53]:
#Dot product
np.dot(mat1,mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [54]:
mat3 = np.dot(mat1, mat2.T)
mat3.shape

(5, 5)

## Dot Product (nut butter sales)

In [55]:
np.random.seed(0)
sales_amounts = np.random.randint(20, size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [56]:
# Create weekly sales Dataframe

weekly_sales = pd.DataFrame(sales_amounts, 
                            index = ["Mon", "Tues", "Wed", "Thurs", "Fri"],
                            columns = ["Almond butter", "Peanut butter", "Cashew butter"])
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [57]:
# Create prices array
prices = np.array([10,8,12])
prices

array([10,  8, 12])

In [58]:
butter_prices = pd.DataFrame(prices.reshape(1,3), index=["Price"], 
 columns=["Almond butter", "Peanut butter", "Cashew butter"])
butter_prices

Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [59]:
total_sales = prices.dot(sales_amounts)

ValueError: shapes (3,) and (5,3) not aligned: 3 (dim 0) != 5 (dim 0)

In [60]:
#Shapes aren't aligned, let's transpose
total_sales = prices.dot(sales_amounts.T)
total_sales

array([240, 138, 458, 232, 142])

In [61]:
# Create daily_sales
butter_prices.shape, weekly_sales.shape

((1, 3), (5, 3))

In [62]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

Mon  Tues  Wed  Thurs  Fri
Price  240   138  458    232  142

In [67]:
weekly_sales["Total ($)"] = daily_sales.T
weekly_sales

Almond butter  Peanut butter  Cashew butter  Totals  Total ($)
Mon               12             15              0     240        240
Tues               3              3              7     138        138
Wed                9             19             18     458        458
Thurs              4              6             12     232        232
Fri                1              6              7     142        142

### Comparison Operators 

In [68]:
a1

array([1, 2, 3])

In [69]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [71]:
bool_array = a1 >= a2
bool_array

array([[ True,  True,  True],
       [False, False, False]])

In [73]:
type(bool_array), bool_array.dtype

(numpy.ndarray, dtype('bool'))

## 5. Sorting arrays

In [75]:
random_array = np.random.randint(10, size=(3,5))
random_array

array([[8, 1, 3, 3, 3],
       [7, 0, 1, 9, 9],
       [0, 4, 7, 3, 2]])

In [76]:
np.sort(random_array)

array([[1, 3, 3, 3, 8],
       [0, 1, 7, 9, 9],
       [0, 2, 3, 4, 7]])

In [77]:
 np.argsort(random_array)

array([[1, 2, 3, 4, 0],
       [1, 2, 0, 3, 4],
       [0, 4, 3, 1, 2]])

In [79]:
np.argmin(a1)

0

In [82]:
random_array

array([[8, 1, 3, 3, 3],
       [7, 0, 1, 9, 9],
       [0, 4, 7, 3, 2]])

In [80]:
np.argmax(random_array,axis=0)

array([0, 2, 2, 1, 1])

In [83]:
np.argmax(random_array,axis=1)

array([0, 3, 2])

## 6. Practical Example - NumPy in Action !!!

<img src="numpy-images/panda.png"/>

In [94]:
# Turn an image into a NumPy array 
from matplotlib.image import imread

panda =imread("numpy-images/panda.png")
type(panda)

numpy.ndarray

In [95]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)

<img src = "numpy-images/car-photo.png"/>

In [102]:
car = imread("numpy-images/car-photo.png")
print(type(car), car.shape)

<class 'numpy.ndarray'> (431, 575, 4)


In [104]:
car[:1]

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]]], dtype=float32)

<img src = "numpy-images/dog-photo.png">

In [106]:
dog = imread("numpy-images/dog-photo.png")