In [2]:
import numpy as np

In [33]:
a1 = np.array([1,2,3])
a2 = np.array([[1,2,3],[4,5,6]])
a3 = np.array([[ [1,2,3], [4,5,6], [7,8,9] ]  ,  [ [10,11,12],[13,14,15],[16,17,18] ]])
print(a1,a2,a3)

[1 2 3] [[1 2 3]
 [4 5 6]] [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [4]:
print(a3.ndim)
print(a3.dtype)
print(a3.mean())

3
int64
5.0


In [5]:
range_array = np.arange(0,10,2)
print(range_array)

[0 2 4 6 8]


In [6]:
#returns random array of integers from low to high
random_array = np.random.randint(0,10, size=(2,4,5))
random_array

array([[[8, 4, 2, 6, 0],
        [8, 0, 2, 7, 4],
        [9, 1, 6, 6, 7],
        [2, 8, 1, 5, 8]],

       [[9, 0, 7, 8, 7],
        [0, 1, 8, 7, 6],
        [0, 6, 6, 6, 8],
        [7, 0, 7, 9, 1]]])

In [7]:
#returns random floats in interval 0 -> 1 in a given size
random_array_2 = np.random.random((3,5))
random_array_2

array([[0.847169  , 0.51815599, 0.79778756, 0.10307323, 0.78981778],
       [0.00774969, 0.08501417, 0.65531964, 0.81567954, 0.07905811],
       [0.15546001, 0.39747176, 0.69027043, 0.66600279, 0.43074045]])

In [8]:
random_array_3 = np.random.rand(3,5)
random_array_3

array([[0.87792316, 0.37939586, 0.07361657, 0.92120402, 0.64156175],
       [0.67523122, 0.28068458, 0.06985541, 0.39116654, 0.80815675],
       [0.13969359, 0.68910295, 0.5696571 , 0.11164765, 0.89451325]])

In [11]:
#pseudo random
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [21]:
np.random.seed(7)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

## 3. Viewing arrays and matrices

In [22]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
a1[0]

1

In [26]:
a2.shape

(2, 3)

In [28]:
a2[0]

array([1, 2, 3])

In [34]:
a3.shape

(2, 3, 3)

In [35]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
 a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [39]:
a4 = np.random.randint(10, size = (2,3,4,5))
a4.shape, a4.ndim, a4

((2, 3, 4, 5),
 4,
 array([[[[9, 3, 4, 0, 3],
          [5, 6, 4, 0, 4],
          [1, 5, 2, 4, 8],
          [7, 5, 7, 5, 3]],
 
         [[7, 6, 2, 3, 1],
          [1, 8, 4, 2, 1],
          [7, 0, 8, 8, 1],
          [2, 3, 0, 1, 1]],
 
         [[5, 5, 6, 0, 9],
          [3, 2, 4, 2, 8],
          [4, 9, 0, 0, 2],
          [6, 3, 9, 5, 4]]],
 
 
        [[[6, 9, 9, 9, 4],
          [8, 2, 4, 6, 5],
          [3, 5, 2, 6, 4],
          [3, 2, 5, 9, 7]],
 
         [[5, 8, 5, 2, 0],
          [9, 3, 2, 2, 4],
          [3, 4, 8, 7, 0],
          [2, 7, 8, 8, 4]],
 
         [[0, 4, 1, 7, 4],
          [9, 0, 1, 0, 6],
          [2, 0, 2, 4, 4],
          [1, 0, 0, 2, 3]]]]))

In [45]:
a4[1,1,0], a4[0,2,1,1:4]


(array([5, 8, 5, 2, 0]), array([2, 4, 2]))

In [49]:
#get the first 4 numbers of the inner most arraya
a4[:,:,:,:4]

array([[[[9, 3, 4, 0],
         [5, 6, 4, 0],
         [1, 5, 2, 4],
         [7, 5, 7, 5]],

        [[7, 6, 2, 3],
         [1, 8, 4, 2],
         [7, 0, 8, 8],
         [2, 3, 0, 1]],

        [[5, 5, 6, 0],
         [3, 2, 4, 2],
         [4, 9, 0, 0],
         [6, 3, 9, 5]]],


       [[[6, 9, 9, 9],
         [8, 2, 4, 6],
         [3, 5, 2, 6],
         [3, 2, 5, 9]],

        [[5, 8, 5, 2],
         [9, 3, 2, 2],
         [3, 4, 8, 7],
         [2, 7, 8, 8]],

        [[0, 4, 1, 7],
         [9, 0, 1, 0],
         [2, 0, 2, 4],
         [1, 0, 0, 2]]]])

## 4. Manipulating and comparing arrays

### Arithmetic

In [52]:
a1

array([1, 2, 3])

In [55]:
ones = np.ones(3)
a1+ones

array([2., 3., 4.])

In [56]:
a1*ones

array([1., 2., 3.])

In [64]:
print(a1,a2)
a1.shape, a2.shape

[1 2 3] [[1 2 3]
 [4 5 6]]


((3,), (2, 3))

In [60]:
a2*a1, a1*a2

(array([[ 1,  4,  9],
        [ 4, 10, 18]]),
 array([[ 1,  4,  9],
        [ 4, 10, 18]]))

In [61]:
a2, a3

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]))

In [62]:
a2*a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 